package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/charmbracelet/huh"
	"github.com/charmbracelet/lipgloss"
	"golang.org/x/term"
)

// isInteractive returns true if stdin is a terminal.
func isInteractive() bool {
	return term.IsTerminal(int(os.Stdin.Fd()))
}

// runSetupWizard guides a new user through interactive configuration.
// Always saves to ~/.ironclaw/config.yaml (global user config).
func runSetupWizard() (string, error) {
	var (
		apiFormat string
		apiKey    string
		baseURL   string
		model     string
		agentMode string
	)

	theme := huh.ThemeBase16()

	// ── Welcome ────────────────────────────────────────────────────
	fmt.Println()
	fmt.Println(lipgloss.NewStyle().
		Bold(true).
		Foreground(lipgloss.Color("#8B6CE0")).
		Render("  🦾  Welcome to IronClaw"))
	fmt.Println(lipgloss.NewStyle().
		Foreground(lipgloss.Color("#787882")).
		Render("  Local-first AI Agent Runtime — let's get you set up."))
	fmt.Println()

	// ── Step 1: API Format ─────────────────────────────────────────
	err := huh.NewForm(
		huh.NewGroup(
			huh.NewNote().
				Title("Step 1/5").
				Description("Choose API format"),
			huh.NewSelect[string]().
				Title("Format").
				Description("Which API format does your provider use?").
				Options(
					huh.NewOption("Anthropic (Claude Sonnet 4, Opus, Haiku)", "claude"),
					huh.NewOption("OpenAI-compatible (GPT-4o, o4-mini, Ollama, vLLM, etc.)", "openai"),
				).
				Height(0).Value(&apiFormat),
		),
	).WithTheme(theme).WithWidth(68).Run()
	if err != nil {
		return "", err
	}

	// ── Step 2: API Key ────────────────────────────────────────────
	defaultKey := "${ANTHROPIC_API_KEY}"
	defaultKeyHint := "uses $ANTHROPIC_API_KEY env var"
	if apiFormat == "openai" {
		defaultKey = "${OPENAI_API_KEY}"
		defaultKeyHint = "uses $OPENAI_API_KEY env var"
	}

	err = huh.NewForm(
		huh.NewGroup(
			huh.NewNote().
				Title("Step 2/5").
				Description("Set your API key"),
			huh.NewInput().
				Title("API Key").
				Description("Leave empty to " + defaultKeyHint).
				Placeholder(defaultKey).
				Value(&apiKey),
		),
	).WithTheme(theme).WithWidth(68).Run()
	if err != nil {
		return "", err
	}
	if apiKey == "" {
		apiKey = defaultKey
	}

	// ── Step 3: Base URL ───────────────────────────────────────────
	defaultBaseURL := "https://api.anthropic.com"
	defaultBaseHint := "official Anthropic API"
	if apiFormat == "openai" {
		defaultBaseURL = "https://api.openai.com/v1"
		defaultBaseHint = "official OpenAI API"
	}

	err = huh.NewForm(
		huh.NewGroup(
			huh.NewNote().
				Title("Step 3/5").
				Description("Set API endpoint (optional)"),
			huh.NewInput().
				Title("Base URL").
				Description("Leave empty for " + defaultBaseHint).
				Placeholder(defaultBaseURL).
				Value(&baseURL),
		),
	).WithTheme(theme).WithWidth(68).Run()
	if err != nil {
		return "", err
	}

	// ── Step 4: Model ──────────────────────────────────────────────
	// Keep this list current — vendors ship new models frequently.
	// Last updated: 2026-06-09
	defaultModel := "claude-sonnet-4-6"

	err = huh.NewForm(
		huh.NewGroup(
			huh.NewNote().
				Title("Step 4/5").
				Description("Choose a model"),
			huh.NewSelect[string]().
				Title("Model").
				Description("Arrow keys to choose, Enter to confirm.").
				OptionsFunc(func() []huh.Option[string] {
					if apiFormat == "claude" {
						return huh.NewOptions(
							"claude-opus-4-8",
							"claude-sonnet-4-6",
							"claude-sonnet-4-5",
							"claude-haiku-4-5",
							"claude-opus-4-20250514",
							"claude-sonnet-4-20250514",
							"claude-3.5-haiku-20241022",
						)
					}
					return huh.NewOptions(
						"gpt-5.4",
						"gpt-5.4-mini",
						"gpt-5.2",
						"gpt-4.1",
						"o4-mini",
						"gpt-4o",
					)
				}, &apiFormat).
				Height(0).Value(&model),
		),
	).WithTheme(theme).WithWidth(68).Run()
	if err != nil {
		return "", err
	}
	if model == "" {
		model = defaultModel
	}

	// ── Step 5: Agent Mode ─────────────────────────────────────────
	err = huh.NewForm(
		huh.NewGroup(
			huh.NewNote().
				Title("Step 5/5").
				Description("Choose agent runtime mode"),
			huh.NewSelect[string]().
				Title("Mode").
				Description("How should the agent process your requests?").
				Options(
					huh.NewOption("Simple — standard linear loop (recommended)", "simple"),
					huh.NewOption("Unified — with parallel tool dispatch", "cognitive"),
				).
				Height(0).Value(&agentMode),
		),
	).WithTheme(theme).WithWidth(68).Run()
	if err != nil {
		return "", err
	}

	// ── Save to global config ──────────────────────────────────────
	home, _ := os.UserHomeDir()
	savePath := filepath.Join(home, ".ironclaw", "config.yaml")

	// ── Build base_url line ────────────────────────────────────────
	baseURLYAML := ""
	if baseURL != "" {
		baseURLYAML = fmt.Sprintf("\n  base_url: \"%s\"", baseURL)
	}

	// ── Generate config ────────────────────────────────────────────
	configYAML := fmt.Sprintf(`# IronClaw configuration — generated by setup wizard.
# Edit this file to adjust settings. Secrets should use ${ENV_VAR} placeholders.
#
# Project-specific overrides: create .ironclaw/ironclaw.yaml in your
# project directory. It merges on top of this global config.

llm:
  provider: %s
  api_key: "%s"%s
  model: %s
  max_tokens: 8192

tui:
  auto_approve: false

agent:
  max_iterations: 20
  mode: %s
  compression:
    strategy: layered
    layers:
      tool_output_reduce_pct: 30
      summarize_pct: 60
      emergency_pct: 85
    token_estimate_ratio: 0.25

store:
  path: "${HOME}/.ironclaw/data/ironclaw.db"

memory:
  storage_type: file
  storage_dir: ~/.ironclaw/memory
  embedding_model: text-embedding-3-small
  openai_api_key: ${OPENAI_API_KEY}

tools:
  bash:
    enabled: true
    timeout: 30s
    requires_approval: true
  file:
    enabled: true
    requires_approval: false
  http:
    enabled: true
    requires_approval: false
    timeout: 30s
  concurrent_execution:
    enabled: true
    max_concurrency: 4
  result_persistence:
    enabled: true
    threshold_bytes: 8192
    preview_chars: 2000
    ttl_hours: 24

permissions:
  default: approve
  rules:
    - tool: bash
      pattern: "git *"
      action: none
    - tool: bash
      pattern: "rm -rf *"
      action: deny
    - tool: file
      path_pattern: "/etc/*"
      action: deny

hooks:
  pre_tool_use:
    - type: safety_analyzer
      config:
        block_patterns:
          - "rm -rf /"
          - "DROP TABLE"
  post_tool_use:
    - type: audit_logger
  on_user_message:
    - type: git_context
      config:
        timeout_ms: 2000
        include_diff_stat: false
    - type: workdir_context
      config:
        include_ls: true
        max_files: 20

log:
  level: info
  format: text
`,
		apiFormat, apiKey, baseURLYAML, model, agentMode)

	// ── Write config ───────────────────────────────────────────────
	dir := filepath.Dir(savePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("create config directory %s: %w", dir, err)
	}
	if err := os.WriteFile(savePath, []byte(configYAML), 0644); err != nil {
		return "", fmt.Errorf("write config: %w", err)
	}

	// ── Done ───────────────────────────────────────────────────────
	fmt.Println()
	box := lipgloss.NewStyle().
		Border(lipgloss.RoundedBorder()).
		BorderForeground(lipgloss.Color("#2EC49C")).
		Padding(1, 2).
		Width(60)

	doneContent :=
		lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("#2EC49C")).Render("✓  Configuration complete!") +
			"\n\n" +
			lipgloss.NewStyle().Foreground(lipgloss.Color("#787882")).Render("Global: "+savePath) + "\n" +
			lipgloss.NewStyle().Foreground(lipgloss.Color("#787882")).Render("Project overrides: create .ironclaw/ironclaw.yaml") + "\n\n" +
			lipgloss.NewStyle().Foreground(lipgloss.Color("#787882")).Render("Run: ironclaw tui")

	fmt.Println(box.Render(doneContent))
	fmt.Println()

	return savePath, nil
}
