package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/term"
)

// isInteractive returns true if stdin is a terminal (user can respond to prompts).
func isInteractive() bool {
	return term.IsTerminal(int(os.Stdin.Fd()))
}

// runSetupWizard guides a new user through interactive configuration.
// Returns the path to the generated config file, or an error.
func runSetupWizard() (string, error) {
	s := bufio.NewScanner(os.Stdin)

	fmt.Println()
	fmt.Println("  🦾  Welcome to IronClaw — Local-first AI Agent Runtime")
	fmt.Println("  Let's set up your configuration. Press Enter to skip any step.")
	fmt.Println()

	// ── 1. Save location ──────────────────────────────────────────
	savePath := promptChoice(s,
		"Where to save the config?",
		[]choice{
			{"1", ".ironclaw/ironclaw.yaml", "current project (recommended)"},
			{"2", "~/.ironclaw/config.yaml", "global default for all projects"},
		},
		"1", // default
	)
	switch savePath {
	case "1":
		savePath = ".ironclaw/ironclaw.yaml"
	case "2":
		home, _ := os.UserHomeDir()
		savePath = filepath.Join(home, ".ironclaw", "config.yaml")
	default:
		savePath = ".ironclaw/ironclaw.yaml"
	}

	// ── 2. LLM Provider ───────────────────────────────────────────
	provider := promptChoice(s,
		"LLM provider",
		[]choice{
			{"1", "claude", "Anthropic Claude (Sonnet 4)"},
			{"2", "openai", "OpenAI (GPT-4o)"},
		},
		"1",
	)
	var providerName, defaultModel string
	switch provider {
	case "1":
		providerName = "claude"
		defaultModel = "claude-sonnet-4-20250514"
	default:
		providerName = "openai"
		defaultModel = "gpt-4o"
	}

	// ── 3. API Key ────────────────────────────────────────────────
	apiKey := promptInput(s, "API key", "")
	if apiKey == "" && providerName == "claude" {
		apiKey = "${ANTHROPIC_API_KEY}"
	}
	if apiKey == "" && providerName == "openai" {
		apiKey = "${OPENAI_API_KEY}"
	}

	// ── 4. Model ──────────────────────────────────────────────────
	model := promptInput(s, "Model", defaultModel)
	if model == "" {
		model = defaultModel
	}

	// ── 5. Agent mode ─────────────────────────────────────────────
	agentMode := promptChoice(s,
		"Agent mode",
		[]choice{
			{"1", "simple", "standard linear loop"},
			{"2", "cognitive", "with replan/reflection"},
		},
		"1",
	)
	modeName := "simple"
	if agentMode == "2" {
		modeName = "cognitive"
	}

	// ── Generate config ───────────────────────────────────────────
	configYAML := fmt.Sprintf(`# IronClaw configuration — generated by setup wizard.
# Edit this file to adjust settings. Secrets should use ${ENV_VAR} placeholders.

llm:
  provider: %s
  api_key: "%s"
  model: %s
  max_tokens: 8192

tui:
  auto_approve: false

agent:
  max_iterations: 20
  mode: %s
  compression:
    strategy: layered
    layers:
      tool_output_reduce_pct: 30
      summarize_pct: 60
      emergency_pct: 85
    token_estimate_ratio: 0.25

store:
  path: "./data/ironclaw.db"

memory:
  storage_type: file
  storage_dir: ~/.IronClaw/memory
  embedding_model: text-embedding-3-small
  openai_api_key: ${OPENAI_API_KEY}

tools:
  bash:
    enabled: true
    timeout: 30s
    requires_approval: true
  file:
    enabled: true
    requires_approval: false
  http:
    enabled: true
    requires_approval: false
    timeout: 30s
  concurrent_execution:
    enabled: true
    max_concurrency: 4
  result_persistence:
    enabled: true
    threshold_bytes: 8192
    preview_chars: 2000
    ttl_hours: 24

permissions:
  default: approve
  rules:
    - tool: bash
      pattern: "git *"
      action: none
    - tool: bash
      pattern: "rm -rf *"
      action: deny
    - tool: file
      path_pattern: "/etc/*"
      action: deny

hooks:
  pre_tool_use:
    - type: safety_analyzer
      config:
        block_patterns:
          - "rm -rf /"
          - "DROP TABLE"
  post_tool_use:
    - type: audit_logger
  on_user_message:
    - type: git_context
      config:
        timeout_ms: 2000
        include_diff_stat: false
    - type: workdir_context
      config:
        include_ls: true
        max_files: 20

log:
  level: info
  format: text
`,
		providerName, apiKey, model, modeName)

	// Ensure parent directory exists
	dir := filepath.Dir(savePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("create config directory %s: %w", dir, err)
	}

	if err := os.WriteFile(savePath, []byte(configYAML), 0644); err != nil {
		return "", fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("\n  ✓ Config saved to %s\n", savePath)
	fmt.Printf("  Run 'ironclaw tui' to start.\n\n")
	return savePath, nil
}

type choice struct {
	key, value, desc string
}

// promptChoice presents options and returns the selected value.
func promptChoice(s *bufio.Scanner, label string, choices []choice, defaultKey string) string {
	fmt.Printf("  %s:\n", label)
	for _, c := range choices {
		fmt.Printf("    [%s] %s — %s\n", c.key, c.value, c.desc)
	}
	fmt.Printf("  Choose [%s]: ", defaultKey)

	if !s.Scan() {
		return defaultValue(choices, defaultKey)
	}
	input := strings.TrimSpace(s.Text())
	if input == "" {
		return defaultValue(choices, defaultKey)
	}
	for _, c := range choices {
		if strings.EqualFold(input, c.key) || strings.EqualFold(input, c.value) {
			return c.value
		}
	}
	return defaultValue(choices, defaultKey)
}

func defaultValue(choices []choice, key string) string {
	for _, c := range choices {
		if c.key == key {
			return c.value
		}
	}
	return choices[0].value
}

// promptInput asks for a text value with a default.
func promptInput(s *bufio.Scanner, label, defaultVal string) string {
	prompt := fmt.Sprintf("  %s", label)
	if defaultVal != "" {
		prompt += fmt.Sprintf(" [%s]", defaultVal)
	}
	prompt += ": "
	fmt.Print(prompt)

	if !s.Scan() {
		return defaultVal
	}
	input := strings.TrimSpace(s.Text())
	if input == "" {
		return defaultVal
	}
	return input
}

// confirm asks a yes/no question.
func confirm(s *bufio.Scanner, question string, defaultYes bool) bool {
	def := "Y/n"
	if !defaultYes {
		def = "y/N"
	}
	fmt.Printf("  %s [%s]: ", question, def)
	if !s.Scan() {
		return defaultYes
	}
	input := strings.TrimSpace(strings.ToLower(s.Text()))
	if input == "" {
		return defaultYes
	}
	return input == "y" || input == "yes"
}
