package a2a

import "time"

// AgentCard is the discovery document that describes an A2A agent.
type AgentCard struct {
	Name          string       `json:"name"`
	Description   string       `json:"description"`
	URL           string       `json:"url"` // base URL for agent API
	Version       string       `json:"version"`
	Capabilities  Capabilities `json:"capabilities"`
	Skills        []AgentSkill `json:"skills"`
	Tools         []AgentTool  `json:"tools,omitempty"`
	Memory        bool         `json:"memory"`
	KnowledgeBase bool         `json:"knowledge_base"`
	CodeIntel     bool         `json:"code_intel"`
}

// Capabilities describes supported A2A transport features.
type Capabilities struct {
	Streaming         bool `json:"streaming"`
	PushNotifications bool `json:"push_notifications"`
}

// AgentSkill describes a callable skill exposed by the agent.
type AgentSkill struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	InputSchema map[string]any `json:"input_schema"`
}

// AgentTool describes a structured tool exposed by the agent.
type AgentTool struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	InputSchema map[string]any `json:"input_schema"`
}

// Task represents a unit of work in A2A.
type Task struct {
	ID        string       `json:"id"`
	State     TaskState    `json:"state"`
	Priority  TaskPriority `json:"priority,omitempty"`
	Input     TaskInput    `json:"input,omitempty"`
	Output    TaskOutput   `json:"output,omitempty"`
	CreatedAt time.Time    `json:"created_at,omitempty"`
	UpdatedAt time.Time    `json:"updated_at,omitempty"`
}

// TaskState describes the current lifecycle state of a task.
type TaskState string

const (
	TaskStatePending    TaskState = "pending"
	TaskStateProcessing TaskState = "processing"
	TaskStateCompleted  TaskState = "completed"
	TaskStateFailed     TaskState = "failed"
)

// TaskPriority controls task scheduling importance.
type TaskPriority string

const (
	PriorityLow    TaskPriority = "low"
	PriorityNormal TaskPriority = "normal"
	PriorityHigh   TaskPriority = "high"
)

// TaskInput is the payload used to create a task.
type TaskInput struct {
	Message string `json:"message"`
	Context string `json:"context,omitempty"`
}

// TaskOutput is the result returned by a completed task.
type TaskOutput struct {
	Text      string     `json:"text"`
	Artifacts []Artifact `json:"artifacts,omitempty"`
}

// Artifact is an output artifact generated by a task.
type Artifact struct {
	Name     string `json:"name"`
	MimeType string `json:"mime_type"`
	Data     string `json:"data"` // base64 for binary, text for text
}

// TaskEvent is a streamed task lifecycle event.
type TaskEvent struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"task_id"`
	Type      string    `json:"type"`
	Data      string    `json:"data"`
	Timestamp time.Time `json:"timestamp"`
}

// PushSubscription registers a webhook for task lifecycle events.
type PushSubscription struct {
	ID          string   `json:"id"`
	CallbackURL string   `json:"callback_url"`
	Events      []string `json:"events"`
}
